baseURL = ""
theme = "zzo"

defaultContentLanguage = "ko"
defaultContentLanguageInSubdir = true
hasCJKLanguage = true

summaryLength = 70

copyright = "&copy;{year}, ZZOSSIG All Rights Reserved"
timeout = 10000
enableEmoji = true
paginate = 13
rssLimit = 100

googleAnalytics = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = true
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false

[outputs]
  home = ["HTML", "RSS", "JSON", "WEBMANIFEST"]

[mediaTypes."application/manifest+json"]
  suffixes = ["webmanifest"]

[outputFormats.webmanifest]
  name = "webmanifest"
  baseName = "webmanifest"
  mediaType = "application/manifest+json"
  rel = "manifest"
  
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"