baseURL = ""
title = "Hugo Zzo Theme"
theme = "zzo"

defaultContentLanguage = "ko"
defaultContentLanguageInSubdir = true
hasCJKLanguage = true

summaryLength = 70

copyright = "&copy;{year}, ZZOSSIG All Rights Reserved"
timeout = 10000
enableEmoji = true
paginate = 13
rssLimit = 100

pygmentsOptions = "linenos=table"
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

googleAnalytics = ""

[outputs]
  home = ["HTML", "RSS", "JSON", "WEBMANIFEST"]

[mediaTypes."application/manifest+json"]
  suffixes = ["webmanifest"]

[outputFormats.webmanifest]
  name = "webmanifest"
  baseName = "webmanifest"
  mediaType = "application/manifest+json"
  rel = "manifest"
  
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"