[build]
publish = "public"
command = "hugo --gc --minify -b https://competent-kepler-84ff52.netlify.com/blog"

[context.production.environment]
HUGO_VERSION = "0.62.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"