logoText = "Zzo"
logoType = "short" # long, short
description = "쪼식이 블로그"
custom_css = []
custom_js = []
useFaviconGenerator = true # https://www.favicon-generator.org/
meta_image = "/images/whoami/avatar.png"
enableGoogleAmp = true

themeOptions = ["hacker", "light", "dark", "solarized", "kimbie"]
notAllowedTypesInHome = ["contact", "talks", "about", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInHomeSidebar = ["about", "archive", "showcase", "gallery", "publication", "presentation", "resume"]
notAllowedTypesInArchive = ["about", "talks", "showcase", "publication", "presentation", "resume"]

# header
homeHeaderType = "text" # text, img, slide

# body
enableBreadcrumb = true
enableSearch = true
enableSearchHighlight = true
enableGoToTop = true
enableWhoami = true
summaryShape = "classic" # card, classic, compact
searchResultPosition = "main" # side, main
archiveGroupByDate = "2006" # "2006-01": group by month, "2006": group by year
archivePaginate = 13
paginateWindow = 1
talksPaginate = 8
talksGroupByDate = "2006"
pubPaginate = 20

# bio, whoami
myname = "최성환"
email = "zzossig@gmail.com"
whoami = "📚Learner🤓Nerd🌐Web Developer"
bioImageUrl = ""
useGravatar = true
location = "Seoul, Korea"
organization = ""
link = "https://zzossig.io"

# sidebar
enableBio = true
enableSidebar = true
enableSidebarTags = true
enableSidebarSeries = true
enableSidebarCategories = true
enableHomeSidebarTitles = true
enableListSidebarTitles = true
enableToc = true
hideToc = false
tocFolding = true
tocPosition = "outer"
enableTocSwitch = true
itemsPerCategory = 5
sidebarPosition = "left"

# footer
showPoweredBy = true
showFeedLinks = true
showSocialLinks = true
enableLangChange = true
enableThemeChange = true

# service
googleTagManager = "" # GTM-XXXXXX
baiduAnalytics = ""
enableBusuanzi = false
busuanziSiteUV = true
busuanziSitePV = true
busuanziPagePV = true

# comment
enableComment = false

[utterances]       # https://utteranc.es/
  owner = "zzossig"              # Your GitHub ID
  repo = "blog"               # The repo to store comments

[socialOptions]
  email = "mailto:zzossig@gmail.com"
  twitter = "https://twitter.com/zzossig"
  github = "https://github.com/zzossig/hugo-theme-zzo"
  stack-overflow = "https://stackoverflow.com/users/11747951/zzossig"
  
[copyrightOptions]
  enableCopyrightLink = true
  copyrightLink = "http://creativecommons.org/licenses/by-sa/4.0/"
  copyrightLinkImage = ""
  copyrightLinkText = "CC BY-SA"
  